---

- hosts: all
  vars:
    epel_testing_enabled: 1
  roles:
    - { role: kostyrevaa.epel, when: "ansible_distribution != 'Fedora'" }

- hosts: all
  vars:
    koji_client_package_only: true
  roles:
    - ansible-koji-client
