---

- hosts: all
  vars:
    epel_testing_enabled: 1
  roles:
    - { role: goozbach.EPEL, when: "ansible_distribution != 'Fedora'" }

- hosts: all
  vars:
    koji_client_package_only: true
  roles:
    - ansible-koji-client
