---
# tasks file for kostyrevaa.koji-client

- name: Main | Remove nodocs from yum.conf
  lineinfile:
    dest: /etc/yum.conf
    state: absent
    regexp: "^tsflags="
  tags:
    - yum-nodocs
    - koji-package

- name: install {{ koji_package }}
  package:
    name: "{{ koji_package }}"
    state: present
  tags:
    - koji-client

- name: Configure /etc/koji.conf
  template:
    src: koji.conf.j2
    dest: /etc/koji.conf
    owner: root
    group: root
    mode: '0644'
  when: not koji_client_package_only
  tags:
    - koji-client
